name=PTSolns_I2Connect_Digit_Display
version=1.0.0
author=PTSolns
maintainer=PTSolns <support@ptsolns.com>
sentence=Library for the PTSolns I2Connect Digit Display module.
paragraph=Provides simple and advanced access to the dual 4-digit displays, while automatically managing I2C communication and hardware multiplexing via the HT16K33A driver.
category=Display
url=https://github.com/PTSolns/I2Connect_Digit_Display
architectures=*
includes=PTSolns_I2Connect_Digit_Display.h
